# Generated by Django 5.2.12 on 2026-04-08 00:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricMotor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mo', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='MO')),
                ('power', models.CharField(max_length=80, verbose_name='Potencia')),
                ('manufacturer', models.CharField(max_length=120, verbose_name='Fabricante')),
                ('frame', models.CharField(max_length=80, verbose_name='Carcaca')),
                ('rpm', models.PositiveIntegerField(verbose_name='RPM')),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tensao')),
                ('current', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Corrente')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observacao')),
                ('status', models.CharField(choices=[('IN_OPERATION', 'Em operação'), ('RESERVE', 'Reserva'), ('INTERNAL_MAINTENANCE', 'Manutenção interna'), ('EXTERNAL_SERVICE', 'Serviço externo'), ('AWAITING_INSTALLATION', 'Aguardando instalação'), ('INACTIVE', 'Inativo')], db_index=True, default='IN_OPERATION', max_length=32, verbose_name='Status')),
                ('registered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de cadastro')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electric_motors', to='unidades.area')),
                ('registered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_electric_motors', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel pelo cadastro')),
            ],
            options={
                'verbose_name': 'Motor eletrico',
                'verbose_name_plural': 'Motores eletricos',
                'ordering': ['mo'],
            },
        ),
        migrations.CreateModel(
            name='BurnedMotorProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data da ocorrencia')),
                ('problem_type', models.CharField(max_length=120, verbose_name='Tipo do problema')),
                ('description', models.TextField(verbose_name='Descricao')),
                ('sent_to_pcm', models.BooleanField(db_index=True, default=False, verbose_name='Enviado para PCM')),
                ('sent_to_pcm_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de envio para PCM')),
                ('in_quotation', models.BooleanField(db_index=True, default=False, verbose_name='Em cotacao')),
                ('payment_approved', models.BooleanField(db_index=True, default=False, verbose_name='Pagamento aprovado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de aprovacao')),
                ('arrived', models.BooleanField(db_index=True, default=False, verbose_name='Chegou')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de chegada')),
                ('sent_for_rewinding', models.BooleanField(default=False, verbose_name='Foi para rebobinamento')),
                ('third_party_company', models.CharField(blank=True, max_length=160, null=True, verbose_name='Empresa terceira')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observacoes')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registrado'), ('AWAITING_PCM', 'Aguardando envio para PCM'), ('PCM_ANALYSIS', 'Em analise no PCM'), ('IN_QUOTATION', 'Em cotacao'), ('AWAITING_APPROVAL', 'Aguardando aprovacao'), ('PAYMENT_APPROVED', 'Pagamento aprovado'), ('IN_REWINDING', 'Em rebobinamento'), ('IN_TRANSPORT', 'Em transporte'), ('RECEIVED', 'Recebido'), ('COMPLETED', 'Concluido')], db_index=True, default='REGISTERED', max_length=32, verbose_name='Status atual')),
                ('registered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_motor_burnout_processes', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_motor_burnout_processes', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burned_processes', to='motores.electricmotor')),
            ],
            options={
                'verbose_name': 'Fluxo de motor queimado',
                'verbose_name_plural': 'Fluxos de motores queimados',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='electricmotor',
            index=models.Index(fields=['area', 'status'], name='motor_area_status_idx'),
        ),
        migrations.AddIndex(
            model_name='electricmotor',
            index=models.Index(fields=['manufacturer', 'frame'], name='motor_maker_frame_idx'),
        ),
        migrations.AddIndex(
            model_name='burnedmotorprocess',
            index=models.Index(fields=['motor', 'status'], name='burn_motor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='burnedmotorprocess',
            index=models.Index(fields=['occurred_at'], name='burn_occurred_idx'),
        ),
    ]
