# Generated by Django 5.2.12 on 2026-04-08 16:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motores', '0001_initial'),
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='electricmotor',
            name='description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Descricao do motor'),
        ),
        migrations.AddField(
            model_name='electricmotor',
            name='is_provisional',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Cadastro provisório'),
        ),
        migrations.AddField(
            model_name='electricmotor',
            name='location_name',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Local / setor'),
        ),
        migrations.CreateModel(
            name='BurnedMotorCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process_code', models.CharField(blank=True, db_index=True, max_length=32, unique=True, verbose_name='Codigo do processo')),
                ('data_origin', models.CharField(choices=[('CATALOG', 'Cadastro existente'), ('MANUAL', 'Informado manualmente'), ('PROVISIONAL', 'Cadastro provisório')], db_index=True, default='MANUAL', max_length=24, verbose_name='Origem dos dados do motor')),
                ('motor_description', models.CharField(blank=True, max_length=160, verbose_name='Descricao do motor')),
                ('motor_mo', models.CharField(blank=True, max_length=80, verbose_name='MO')),
                ('motor_power', models.CharField(blank=True, max_length=80, verbose_name='Potencia')),
                ('motor_manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Fabricante')),
                ('motor_frame', models.CharField(blank=True, max_length=80, verbose_name='Carcaca')),
                ('motor_rpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='RPM')),
                ('motor_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tensao')),
                ('motor_current', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Corrente')),
                ('motor_location', models.CharField(blank=True, max_length=160, verbose_name='Local / setor')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data da ocorrencia')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data do registro')),
                ('requester_name', models.CharField(max_length=255, verbose_name='Solicitante')),
                ('problem_type', models.CharField(max_length=120, verbose_name='Tipo do problema')),
                ('defect_description', models.TextField(verbose_name='Descricao do defeito')),
                ('technical_notes', models.TextField(blank=True, verbose_name='Observacoes tecnicas')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Critica')], db_index=True, default='MEDIUM', max_length=24, verbose_name='Prioridade')),
                ('needs_pcm', models.BooleanField(default=True, verbose_name='Precisa enviar ao PCM')),
                ('sent_to_pcm', models.BooleanField(db_index=True, default=False, verbose_name='Enviado ao PCM')),
                ('sent_to_pcm_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de envio ao PCM')),
                ('pcm_responsible', models.CharField(blank=True, max_length=140, verbose_name='PCM responsavel')),
                ('sent_to_finance', models.BooleanField(db_index=True, default=False, verbose_name='Enviado ao financeiro')),
                ('finance_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de envio ao financeiro')),
                ('approved', models.BooleanField(db_index=True, default=False, verbose_name='Pedido aprovado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da aprovacao')),
                ('solution_type', models.CharField(choices=[('UNDER_EVALUATION', 'Em avaliacao'), ('NEW_PURCHASE', 'Compra de motor novo'), ('REWINDING', 'Rebobinamento'), ('INTERNAL_REPAIR', 'Reparo interno'), ('THIRD_PARTY_REPAIR', 'Reparo terceirizado'), ('SCRAP', 'Sucateamento')], default='UNDER_EVALUATION', max_length=32, verbose_name='Tipo de solucao')),
                ('purchase_new_motor', models.BooleanField(default=False, verbose_name='Compra de motor novo')),
                ('rewinding_required', models.BooleanField(default=False, verbose_name='Precisa rebobinamento')),
                ('third_party_company', models.CharField(blank=True, max_length=160, verbose_name='Empresa terceira')),
                ('third_party_contact', models.CharField(blank=True, max_length=160, verbose_name='Contato da empresa')),
                ('freight_requested', models.BooleanField(db_index=True, default=False, verbose_name='Frete/coleta solicitado')),
                ('pickup_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da coleta')),
                ('expected_return_at', models.DateTimeField(blank=True, null=True, verbose_name='Data prevista de retorno')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de chegada')),
                ('progress_notes', models.TextField(blank=True, verbose_name='Observacoes do andamento')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IDENTIFIED', 'Identificado na oficina'), ('AWAITING_PCM', 'Aguardando envio ao PCM'), ('SENT_TO_PCM', 'Enviado ao PCM'), ('PCM_ANALYSIS', 'Em analise no PCM'), ('SENT_TO_FINANCE', 'Enviado ao financeiro'), ('AWAITING_APPROVAL', 'Aguardando aprovacao'), ('APPROVED', 'Aprovado'), ('AWAITING_VENDOR', 'Aguardando empresa terceira'), ('AWAITING_FREIGHT', 'Aguardando coleta/frete'), ('IN_TRANSPORT', 'Em transporte'), ('IN_REWINDING', 'Em rebobinamento'), ('AWAITING_RETURN', 'Aguardando retorno'), ('RECEIVED', 'Recebido'), ('COMPLETED', 'Concluido'), ('CANCELLED', 'Cancelado')], db_index=True, default='OPEN', max_length=40, verbose_name='Status atual')),
                ('pcm_email_sent', models.BooleanField(db_index=True, default=False, verbose_name='E-mail enviado ao PCM')),
                ('pcm_email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de envio do e-mail ao PCM')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burned_motor_cases', to='unidades.area')),
                ('motor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burned_cases', to='motores.electricmotor', verbose_name='Motor relacionado')),
                ('opened_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_burned_motor_cases', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel pela abertura')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_burned_motor_cases', to=settings.AUTH_USER_MODEL, verbose_name='Ultima atualizacao por')),
            ],
            options={
                'verbose_name': 'Processo de motor queimado',
                'verbose_name_plural': 'Processos de motores queimados',
                'ordering': ['-occurred_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BurnedMotorCaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(default='note', max_length=32, verbose_name='Tipo do evento')),
                ('title', models.CharField(max_length=160, verbose_name='Titulo')),
                ('details', models.TextField(blank=True, verbose_name='Detalhes')),
                ('event_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data do evento')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burned_motor_case_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsavel')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='motores.burnedmotorcase')),
            ],
            options={
                'verbose_name': 'Evento do processo de motor queimado',
                'verbose_name_plural': 'Eventos do processo de motor queimado',
                'ordering': ['-event_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='burnedmotorcase',
            index=models.Index(fields=['area', 'status'], name='burned_case_area_status_idx'),
        ),
        migrations.AddIndex(
            model_name='burnedmotorcase',
            index=models.Index(fields=['process_code'], name='burned_case_code_idx'),
        ),
        migrations.AddIndex(
            model_name='burnedmotorcase',
            index=models.Index(fields=['expected_return_at'], name='burned_case_return_idx'),
        ),
        migrations.AddIndex(
            model_name='burnedmotorcaseevent',
            index=models.Index(fields=['case', 'event_at'], name='burned_case_event_idx'),
        ),
    ]
