# Generated by Django 5.2.12 on 2026-04-03 23:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOutboxEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='pwa', max_length=80)),
                ('entity_name', models.CharField(db_index=True, max_length=120)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('action', models.CharField(max_length=40)),
                ('payload', models.JSONField()),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Item de sincronização',
                'verbose_name_plural': 'Itens de sincronização',
                'ordering': ['-received_at'],
            },
        ),
    ]
