# Generated by Django 5.2.12 on 2026-04-03 23:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('entity_name', models.CharField(db_index=True, max_length=120)),
                ('entity_id', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSED', 'Processado'), ('ERROR', 'Erro')], db_index=True, default='PENDING', max_length=16)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='unidades.area')),
            ],
            options={
                'verbose_name': 'Evento de notificação',
                'verbose_name_plural': 'Eventos de notificação',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
