# Generated by Django 5.2.12 on 2026-04-13 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Fabrica',
                'verbose_name_plural': 'Fabricas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeProdutiva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_produtivas', to='unidades.fabrica')),
            ],
            options={
                'verbose_name': 'Unidade produtiva',
                'verbose_name_plural': 'Unidades produtivas',
                'ordering': ['fabrica__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('fabrica', 'code'), name='uq_unidade_produtiva_fabrica_code')],
            },
        ),
    ]
