# Generated by Django 5.2.12 on 2026-04-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_fabrica_unidadeprodutiva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['area__name', 'unidade__fabrica__name', 'unidade__name', 'sector', 'name'], 'verbose_name': 'Localizacao', 'verbose_name_plural': 'Localizacoes'},
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='uq_location_name_sector_area',
        ),
        migrations.AddField(
            model_name='location',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='unidades.unidadeprodutiva'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('name', 'sector', 'area', 'unidade'), name='uq_location_name_sector_area_unidade'),
        ),
    ]
