# Generated by Django 5.2.12 on 2026-04-03 23:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnedMotorRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_equipment_tag', models.CharField(db_index=True, max_length=80)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('diagnosis', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('UNDER_ANALYSIS', 'Em análise'), ('SENT_TO_REPAIR', 'Enviado para reparo'), ('REPAIRED', 'Reparado'), ('DISCARDED', 'Descartado')], default='OPEN', max_length=32)),
                ('notes', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burned_motor_records', to='unidades.area')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burned_motor_records', to='equipamentos.motor')),
                ('recorded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burned_motor_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de motor queimado',
                'verbose_name_plural': 'Registros de motores queimados',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('MAINTENANCE', 'Manutenção'), ('CALIBRATION', 'Calibração'), ('THIRD_PARTY_REPAIR', 'Reparo terceirizado')], max_length=32)),
                ('service_status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em andamento'), ('SENT_TO_VENDOR', 'Enviado ao fornecedor'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='OPEN', max_length=32)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expected_return_at', models.DateTimeField(blank=True, null=True)),
                ('actual_return_at', models.DateTimeField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=160, null=True)),
                ('vendor_reference', models.CharField(blank=True, max_length=80, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_service_requests', to='unidades.area')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='equipamentos.instrument')),
                ('registered_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de serviço de instrumento',
                'verbose_name_plural': 'Solicitações de serviço de instrumentos',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=255)),
                ('status_after', models.CharField(blank=True, max_length=80, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='equipamentos.equipment')),
                ('moved_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to=settings.AUTH_USER_MODEL)),
                ('new_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_movements', to='unidades.location')),
                ('previous_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_movements', to='unidades.location')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-moved_at'],
            },
        ),
    ]
