# Generated by Django 5.2.12 on 2026-04-04 00:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('equipamentos', '0001_initial'),
        ('ocorrencias', '0001_initial'),
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentservicerequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Solicitacao de servico de instrumento', 'verbose_name_plural': 'Solicitacoes de servico de instrumentos'},
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['-moved_at'], 'verbose_name': 'Movimentacao', 'verbose_name_plural': 'Movimentacoes'},
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.CharField(choices=[('FAILURE', 'Falha'), ('ANOMALY', 'Anomalia'), ('INSPECTION', 'Inspecao'), ('PREVENTIVE', 'Preventiva'), ('OTHER', 'Outro')], db_index=True, default='FAILURE', max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('IN_PROGRESS', 'Em andamento'), ('WAITING_PARTS', 'Aguardando recurso'), ('RESOLVED', 'Resolvida'), ('CANCELLED', 'Cancelada')], db_index=True, default='OPEN', max_length=32)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('had_downtime', models.BooleanField(db_index=True, default=False)),
                ('downtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='unidades.area')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='equipamentos.equipment')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='unidades.location')),
                ('reported_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_occurrences', to=settings.AUTH_USER_MODEL)),
                ('responsible_collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='colaboradores.collaborator')),
            ],
            options={
                'verbose_name': 'Ocorrencia',
                'verbose_name_plural': 'Ocorrencias',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
    ]
