# Generated by Django 5.2.12 on 2026-04-04 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('equipamentos', '0001_initial'),
        ('ocorrencias', '0002_alter_instrumentservicerequest_options_and_more'),
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['area', 'status', 'occurred_at'], name='occ_area_status_occurred_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['equipment', 'occurred_at'], name='occ_equipment_occurred_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['classification', 'occurred_at'], name='occ_class_occurred_idx'),
        ),
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('downtime_minutes__isnull', True), ('had_downtime', False)), models.Q(('downtime_minutes__isnull', False), ('had_downtime', True)), _connector='OR'), name='occurrence_downtime_consistency'),
        ),
    ]
