# Generated by Django 5.2.12 on 2026-04-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_occurrence_occ_area_status_occurred_idx_and_more'),
        ('unidades', '0003_alter_area_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='unidades.unidadeprodutiva'),
        ),
    ]
