# Generated by Django 5.2.12 on 2026-04-13 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('unidades', '0002_fabrica_unidadeprodutiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fabrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_users', to='unidades.fabrica'),
        ),
        migrations.AddField(
            model_name='user',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='unidades.unidadeprodutiva'),
        ),
    ]
