# Generated by Django 5.2.12 on 2026-04-03 23:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=160)),
                ('work_order_number', models.CharField(db_index=True, max_length=80)),
                ('expected_return_at', models.DateTimeField(blank=True, null=True)),
                ('actual_return_at', models.DateTimeField(blank=True, null=True)),
                ('service_status', models.CharField(choices=[('OPEN', 'Aberta'), ('IN_PROGRESS', 'Em andamento'), ('RETURNED', 'Retornada'), ('DELAYED', 'Atrasada'), ('CANCELLED', 'Cancelada')], db_index=True, default='OPEN', max_length=32)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments_metadata', models.JSONField(blank=True, null=True)),
                ('authorized_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_service_orders', to=settings.AUTH_USER_MODEL)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_service_orders', to='equipamentos.motor')),
                ('registered_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_service_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordem de serviço externa',
                'verbose_name_plural': 'Ordens de serviço externas',
                'ordering': ['-sent_at'],
            },
        ),
    ]
