# Generated by Django 5.2.12 on 2026-04-03 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('tag', models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=120, null=True)),
                ('model', models.CharField(blank=True, max_length=120, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('GENERIC', 'Genérico'), ('MOTOR', 'Motor'), ('INSTRUMENT', 'Instrumento')], db_index=True, default='GENERIC', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('UNDER_MAINTENANCE', 'Em manutenção'), ('EXTERNAL_SERVICE', 'Serviço externo'), ('INACTIVE', 'Inativo')], db_index=True, default='ACTIVE', max_length=32)),
                ('registered_at', models.DateTimeField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='unidades.area')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='unidades.location')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='instrument', serialize=False, to='equipamentos.equipment')),
                ('unique_identifier', models.CharField(db_index=True, max_length=80, unique=True)),
                ('instrument_type', models.CharField(max_length=120)),
                ('current_status', models.CharField(choices=[('INSTALLED', 'Instalado'), ('IN_STOCK', 'Em estoque'), ('IN_CALIBRATION', 'Em calibração'), ('IN_MAINTENANCE', 'Em manutenção'), ('AWAITING_INSTALLATION', 'Aguardando instalação'), ('INACTIVE', 'Inativo')], db_index=True, default='IN_STOCK', max_length=32)),
                ('calibration_due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': ['unique_identifier'],
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='motor', serialize=False, to='equipamentos.equipment')),
                ('unique_identifier', models.CharField(db_index=True, max_length=80, unique=True)),
                ('current_status', models.CharField(choices=[('IN_OPERATION', 'Em operação'), ('RESERVE', 'Reserva'), ('INTERNAL_MAINTENANCE', 'Manutenção interna'), ('EXTERNAL_SERVICE', 'Serviço externo'), ('AWAITING_INSTALLATION', 'Aguardando instalação'), ('INACTIVE', 'Inativo')], db_index=True, default='IN_OPERATION', max_length=32)),
                ('last_internal_service_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Motor',
                'verbose_name_plural': 'Motores',
                'ordering': ['unique_identifier'],
            },
        ),
    ]
