# Generated by Django 5.2.12 on 2026-04-03 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('ADMIN', 'Admin'), ('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor'), ('LIDER', 'Líder'), ('INSPETOR', 'Inspetor'), ('MANUTENTOR', 'Manutentor')], max_length=32, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Papéis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_area_assignments', to='unidades.area')),
            ],
            options={
                'verbose_name': 'Vinculação usuário-área',
                'verbose_name_plural': 'Vinculações usuário-área',
            },
        ),
    ]
